language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover